### ISSUE TITLE
Problem with compile and install

### ISSUE THREAD

**Issue by aangelov971** [EtheaDev/DelphiGoogleMap#4]
I try to compile error appears 
[dcc32 Fatal Error] Vcl.GoogleMap.pas(1): Internal Error: AV004778D9-R00000000-0
I read about error and set delphi compiler option to MSBuild externaly to true. error continue toa apear. It's not a syntax error. What should I do next?

**Comment by carloBarazzetta** [comment]
what version of delphi are you using to compile?

**Comment by anastasangelov** [comment]
10.4.2 Sydney

**Comment by carloBarazzetta** [comment]
OK, I've notice that this problem was introduced by the last pull requested by @littleearth: it seems only a problem to compile the package in D10.4.2: the same package in D11 builds without problems, and also the demo works fine in D10.4.2... I'll investigating... I've the component of the previous version installed into 10.4.2 IDE

**Comment by anastasangelov** [comment]
Ty,Carlo, I will wait for some solution and I will try with resources used for compile.Good to know that I am not alone.

**Comment by aangelov971** [comment]
Works. ty
